#Create a makefile that compiles the .C files and creates a makeAnimals
#executable.
#
#Add macros for the compiler and the compiler flags.
#The compiler flags to add are: -c, -Wall, -g, -std=c++11
#Add a macro that defines the object files to be linked together
#to create the executable.
#Add suffix rule that specifies how to create a .o out of a .C file.
#Add targets for: the executable (call it makeAnimals), each .o, and clean.
#The very first target in the makefile should be the executable, 
#makeAnimals.
#You'll need to look at each .C file to determine what dependencies 
#to add, but you won't need to add a dependence for every included
#header file. Specifically, you don't needed dependences for standard 
#header files (those in angled brackets). 
#Also, the make utility figures out some dependences without 
#you specifying them. 
#The clean command below the clean target should delete all of the .o files.
#Do not add unnecessary commands or dependencies. 
#Answer the questions in the second page of the quiz.
