#Create a makefile that will compile the .C files in the source
#directory and create a sortProg executable.
#
#Add macros for the compiler and the compiler flags.
#The compiler flags to add are: -c, -Wall, -g, -std=c++11, -I ../include
#Add a macro that defines the object files to be linked together
#to create the executable.
#Don't use PATH or the name of any the Linux environment variables
#as a macro name.  (You'll regret it if you do.)
#Add suffix rule that specifies how to create a .o out of a .C file.
#You'll need a target for the executable (sortProg), each .o, install, and clean.
#The very first target in the makefile should be for the executable,
#sortProg.
#Create a bin directory that is at the same level as the source and include directories.
#The install command should create the executable and move it to the ../bin directory.
#The clean command should delete the .o files.
#Do not add unnecessary commands and dependences.
#Answer the questions in the third part of quiz.

